name: Quality control checks

on:
  push:
    branches:
      - main

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'

      - run: flutter pub get

      - run: flutter analyze

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'

      - run: flutter pub get

      - run: flutter test